kind: pipeline
type: docker
name: Lint

platform:
  os: linux
  arch: arm64

steps:
  - name: Lint
    image: python:latest
    environment:
      PIP_INDEX_HOST:
        from_secret: PIP_INDEX_HOST
      PIP_INDEX_URL:
        from_secret: PIP_INDEX_URL
    commands:
      - pip config set global.index-url $PIP_INDEX_URL; pip config set global.trusted-host $PIP_INDEX_HOST; pip install --upgrade pip poetry
      - poetry install
      - poetry run flake8
